name: Test Upload to GitHub Actions
on: [push, pull_request]

jobs:
  build:
    name: upload-test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Upload test_report_1.json
        uses: actions/upload-artifact@v3
        with:
          path: test_report_1.json
      - name: Download test_report_1.json from `main` branch
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-upload.yml
          branch: main
      - name: print markdown in run
        run: cat results.md >> $GITHUB_STEP_SUMMARY
      - name: create comment with results
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-numer: ${{ steps.find-pull-request.outputs.number }}
          comment-author: 'github-actions[bot]'
          body: |
            My comment
