name: Test Upload to GitHub Actions
on: [push, pull_request]

jobs:
  build:
    name: upload-test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Upload test_report_1.json
        uses: actions/upload-artifact@v3
        with:
          path: test_report_1.json
      - name: Download test_report_1.json from `main` branch
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-upload.yml
          branch: main
      - name: Display structure of downloaded files
        run: ls -R
      - name: cat test_report_1.json
        run: cat ./artifact/test_report_1.json
