name: Test Upload to GitHub Actions
on: [push, pull_request]

jobs:
  build:
    name: upload-test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Upload test_report_1.json
        uses: actions/upload-artifact@v3
        with:
          path: test_report_1.json
      - name: Download test_report_1.json from `main` branch
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-upload.yml
          branch: main
      - name: print markdown in run
        run: cat results.md >> $GITHUB_STEP_SUMMARY
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: This comment was written by a bot!
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            This comment was written by a bot!
          reactions: rocket

      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            This comment has been updated!
          reactions: hooray
